version: '3'

services:
  api:
    image: api
    build:
      context: ./api
      target: prod
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
    healthcheck:
      test: ["CMD", "curl http://localhost:9808/health/live | grep LIVE"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '9808'
    deploy:
      mode: replicated
      replicas: ${API_REPLICAS:-2}
      endpoint_mode: dnsrr
    networks:
      - api-net
  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD:-admin} 
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-admin} ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redisdata:/data
    networks:
      - api-net
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - '8080:8080'
    networks:
      - api-net

volumes:
  redisdata:

networks:
  api-net:
    name: api-net

