version: '3'

services:
  api:
    image: api
    build:
      context: ./api
      target: prod
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
    ports:
      - '9808:9808'
    networks:
      - api-net
  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD:-admin} 
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-admin} ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - redisdata:/data
    networks:
      - api-net

volumes:
  redisdata:

networks:
  api-net:
    name: api-net

