version: '3'

services:
  api-test:
    image: api-test
    build:
      context: ./api
      target: test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - GIN_MODE=debug
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=test
    networks:
      - api-test-net
  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel notice --requirepass test
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a 'test' ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - api-test-net

networks:
  api-test-net:
    name: api-test-net

